version: "3.8"

services:
  tab-blaster-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - FIREBASE_CREDENTIALS_FILE=/app/firebase-credentials.json
    env_file:
      - .env
    volumes:
      # Mount only necessary files for production
      - ./.env:/app/.env:ro
      # Mount Firebase credentials file
      - ./my-apps-gmoney-firebase-adminsdk-tx7fe-4c0600fe18.json:/app/firebase-credentials.json:ro
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:8080/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
